### ISSUE TITLE
KNOWN ISSUE: Random null pointer exception on inventory click event

### ISSUE THREAD

**Issue by jamesafk** [jamesafk/SimpleAddons#10]
Random error returning this message:

`[16:23:29 WARN]: java.lang.NullPointerException
[16:23:29 WARN]:        at java.util.Objects.requireNonNull(Unknown Source)
[16:23:29 WARN]:        at com.jamesafk.simpleaddons.events.inventoryEvents.onClick(inventoryEvents.java:38)
[16:23:29 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor250.execute(Unknown Source)
[16:23:29 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:23:29 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:23:29 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:23:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2427)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
[16:23:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[16:23:29 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by jamesafk** [comment]
Progress update: Found issue source and working on patching it :)

**Comment by jamesafk** [comment]
Update: Cannot currently find a fix. Suppressed the warnings it gives in console. I do not believe the issue breaks anything currently. If it does for you, please report it to me by creating an issue on github!
