### ISSUE TITLE
SimpleAddons Disabled during launch...

### ISSUE THREAD

**Issue by RelicRonk** [jamesafk/SimpleAddons#17]
I'm using Pape-Spigot from https://papermc.io/downloads Build #202
[09:50:40] [Server thread/ERROR]: Error occurred while enabling SimpleAddons v2.2.1 (Is it up to date?)
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_265]
        at com.jamesafk.simpleaddons.main.onEnable(main.java:191) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-202]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-202]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-202]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-202]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[09:50:40] [Server thread/INFO]: [SimpleAddons] Disabling SimpleAddons v2.2.1
[09:50:40] [Server thread/INFO]: ===================================
[09:50:40] [Server thread/INFO]: Simple Addons is shutting down!
[09:50:40] [Server thread/INFO]: Thank you for using Simple Addons
[09:50:40] [Server thread/INFO]: ===================================

**Comment by jamesafk** [comment]
Hi,
This is the code that your server is having an issue with
`        Location spawnpoint = Objects.requireNonNull(getServer().getWorld("World")).getSpawnLocation();`
Essentially this is trying to find the spawn point of "world"
I will get to work on fixing this and release a patch :)

**Comment by jamesafk** [comment]
I think I fixed the issue:
https://github.com/jamesafk/SimpleAddons/releases/tag/2.2.2-BETA
If you could test this for me that would be great!

**Comment by RelicRonk** [comment]
Ran a test. 

[10:44:10 INFO]: [SimpleAddons] Enabling SimpleAddons v2.2.2-BETA
[10:44:10 INFO]: ===================================
[10:44:10 INFO]: You are using Simple Addons
[10:44:10 INFO]: Version 2.2.2-BETA
[10:44:10 INFO]: Developed by JamesAfk
[10:44:10 INFO]: Thank you for using Simple Addons
[10:44:10 INFO]: ===================================
[10:44:10 INFO]: CONSOLE: Reload complete.
[10:44:10 WARN]: Can't keep up! Is the server overloaded? Running 7410ms or 148 ticks behind
[10:44:10 INFO]: Timings Reset
[10:44:10 WARN]: [SimpleAddons] There is a new update available!

**Comment by jamesafk** [comment]
That can't keep up looks a lil sus. It might be because of reload though, that can it to lag a little. Tell me if you have any more issues and I'll release the patch tommorow

**Comment by RelicRonk** [comment]
> That can't keep up looks a lil sus. It might be because of reload though, that can it to lag a little. Tell me if you have any more issues and I'll release the patch tommorow

Hey Sorry, dont worry about the Can't keep up, thats not the addon! it does that even without ;) didnt even notice it in that portion of the log or i would have deleted it :)

**Comment by jamesafk** [comment]
Awesome, thank you!

**Comment by jamesafk** [comment]
[Bug Fix](https://github.com/jamesafk/SimpleAddons/releases/tag/2.2.2)
